# zsh settings

# Improve history
HISTSIZE=100000000
HISTFILESIZE=2000000
setopt CORRECT

# Powerline exports:
POWERLINE_RIGHT_A="exit-status-on-fail"
BULLETTRAIN_STATUS_SHOW=true
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_EXEC_TIME_SHOW=true
BULLETTRAIN_DIR_EXTENDED=2
#export TERM="xterm-256color"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-flow colored-man-pages pip colorize virtualenv django zsh-autosuggestions nvm systemd cargo tpm)

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

if [[ ! -d $HOME/.vim.backup ]]; then
    mkdir -p $HOME/.vim.backup
fi
export EDITOR="$(if [[ -f /usr/bin/nvim ]]; then echo 'nvim'; else echo 'vim'; fi)"


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
if [ -f ~/.profile ]; then
    . ~/.profile
fi 
 

# Example aliases
alias rm="rm"
alias ll="ls -larth"
alias lm="ls -laShr"
alias cp="cp"

# BASE16_SHELL=$HOME/.config/base16-shell/
# [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


# Bash functions
function cs() { cd "$@" && ls -lh --color='always'; }
function ce() { cd "$@" && exa -lg; }
function cx() { cd "$@" && exa -lg; }


# Rust exports
export CARGO_HOME="$HOME/.cargo"
if [[ -s $CARGO_HOME/env ]]; then
	export CARGO_INCREMENTAL=1
    source $CARGO_HOME/env
    fpath+=~/.zfunc
    export LD_LIBRARY_PATH="$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:$LD_LIBRARY_PATH"
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src/"
fi


export BULLETTRAIN_PROMPT_ORDER=(time context status custom dir virtualenv git cmd_exec_time)
export BULLETTRAIN_VIRTUALENV_BG="green"
export BULLETTRAIN_VIRTUALENV_FG="black"
# export BULLETTRAIN_DIR_BG="cyan"
# export BULLETTRAIN_DIR_FG="black"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
#bind -x '"\C-p": vim $(fzf);'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# Base16 Monokai
# Author: Wimer Hazenberg (http://www.monokai.nl)
_gen_fzf_default_opts() {
    local color00='#272822'
    local color01='#383830'
    local color02='#49483e'
    local color03='#75715e'
    local color04='#a59f85'
    local color05='#f8f8f2'
    local color06='#f5f4f1'
    local color07='#f9f8f5'
    local color08='#f92672'
    local color09='#fd971f'
    local color0A='#f4bf75'
    local color0B='#a6e22e'
    local color0C='#a1efe4'
    local color0D='#66d9ef'
    local color0E='#ae81ff'
    local color0F='#cc6633'

    export FZF_DEFAULT_OPTS="
      --height 40% --border
      --color=bg+:$color01,bg:$color00,spinner:$color0C,hl:$color0D
      --color=fg:$color04,header:$color0D,info:$color0A,pointer:$color0C
      --color=marker:$color0C,fg+:$color06,prompt:$color0A,hl+:$color0D
    "
}

_gen_fzf_default_opts

