//! This is the entry point from where the data will be gathered, processed if needed.
//! The implementation will be kept as simple as possible, with as little generic as possible for
//! example, because you know, knowledge is power, and I don't want this work to be reused
//! by greedy people ;)

mod wifi;

pub use self::wifi::Wifi;
use std::collections::HashMap;
use std::io::{Read, Result as IOResult};

/// This is where we gather intel about the network capability of a Linux system.
const NET_CARDS_ROOT_PATH: &str = "/sys/class/net/";

pub trait Sensor {
    fn fetch(&mut self) -> IOResult<u32>;
    // fn write(&mut self) -> Result<()>;
    // fn store(&mut self) -> Result<u32, std::io::Error>;
    // fn flush(&mut self) -> Result<()>;
    // fn pop(&mut self) -> Result<()>;
}
//
// /// We define here our own Error kind.
// #[derive(Debug)]
// enum SError {
//     /// This is an Error generated by I/O.
//     Io(IOError),
// }

/// List all the available network card on the system along with their mac addresses.
pub fn list_network_interfaces() -> std::io::Result<HashMap<String, String>> {
    use walkdir::WalkDir;

    let mut card_hm: HashMap<String, String> = HashMap::new();

    // First we need to list all the available network cards on the system
    // Skipping the first entry because it's the root path we are actually listing
    for entry in WalkDir::new(NET_CARDS_ROOT_PATH)
        .into_iter()
        .filter_map(|p| p.ok())
        .skip(1)
    {
        let path = entry.path().display().to_string();

        match path.split('/').collect::<Vec<&str>>().last() {
            Some(interface_name) => {
                let iface_name = interface_name.to_string();

                // Let's focus only on the wireless cards
                // They should start with the letters "wl"
                if iface_name.to_string().starts_with("wl") {
                    // And then, we fetch their mac addresses
                    let mac_address_file = std::path::Path::new(&path.to_owned()).join("address");

                    if let Ok(mut file) = std::fs::File::open(&mac_address_file) {
                        let mut buf = String::new();
                        file.read_to_string(&mut buf)?;
                        let mac_address = buf.trim();
                        debug!("{:?} {}", mac_address_file, mac_address);
                        card_hm.insert(iface_name, mac_address.to_owned());
                    }
                }
            }
            _ => {
                crit!("No network cards detected from {}", NET_CARDS_ROOT_PATH);
            }
        }
    }

    Ok(card_hm)
}
